version: '3'

services:
  lab:
    build: ./
    image: usc-price-workshop
    container_name: usc-price-workshop
    volumes:
     - ./:/app
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=1
    command: ["/bin/sh","-c","pip install -e /app && jupyter-lab --no-browser --ip=\"*\" --allow-root --port=8888 --NotebookApp.notebook_dir=/app --NotebookApp.terminado_settings='{\"shell_command\": [\"bash\"]}' --LabApp.token=\"\" --LabApp.password=\"\""]

